# Local deployment values for webui-adk-chart
# This file contains settings optimized for local development

# Global settings
replicaCount: 1
releaseName: "webui-adk-local"

# Persistence Configuration for local development
persistence:
  enabled: true
  # Use default storage class for local development
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  # Smaller size for local development
  size: 5Gi

# Open WebUI Frontend Configuration
openWebUI:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: IfNotPresent
  service:
    # Use NodePort for local access
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: ${SERVICE_NODE_PORT}
  # OIDC/SSO Configuration - enabled for local development
  sso:
    enabled: true
    clientId: "${OAUTH_CLIENT_ID}"
    clientSecret: "${OAUTH_CLIENT_SECRET}"
    providerUrl: "https://accounts.google.com/.well-known/openid-configuration"
    providerName: "Google"
    scopes: "openid email profile"
  # Auto-create admin account configuration
  admin:
    email: "${ADMIN_EMAIL}"
    password: "${ADMIN_PASSWORD}"
    autoCreate: true
  # Authentication settings
  auth:
    disableSignup: false  # Allow new users via both SSO and password
    enableOAuth: true
    enablePasswordLogin: true  # Enable username/password login
    requireEmailVerification: false

# ADK Backend Configuration
adkBackend:
  image:
    # Use the locally built ADK backend image
    repository: "adk-backend"
    tag: "local"
    pullPolicy: IfNotPresent
  port: ${ADK_BACKEND_PORT}
  gcp:
    projectId: "${GCP_PROJECT_ID}"
    # Don't mount local credentials in GKE Autopilot - use Workload Identity instead
    credentialsPath: ""
  env:
    # Enable Vertex AI for local testing with credentials
    GOOGLE_GENAI_USE_VERTEXAI: "TRUE"
    # Disable local mode since we have credentials
    ADK_LOCAL_MODE: "FALSE"

# Ingress Configuration - disabled for local development
ingress:
  enabled: false
  className: ""
  host: "localhost"
  annotations: {}
  tls:
    enabled: false
    secretName: ""

# Local development specific settings
local:
  # Expose services via NodePort for easy access
  exposeServices: true
  # Use host networking for easier debugging
  hostNetwork: false

# Ollama Proxy Configuration
ollamaProxy:
  image:
    # Use the locally built Ollama proxy image
    repository: "ollama-proxy"
    tag: "local"
    pullPolicy: IfNotPresent
  port: ${OLLAMA_PROXY_PORT}
  logLevel: "INFO"
