# Local deployment values for webui-adk-chart
# This file contains settings optimized for local development

# Global settings
replicaCount: 1
releaseName: "webui-adk-local"

# Persistence Configuration for local development
persistence:
  enabled: true
  # Use default storage class for local development
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  # Smaller size for local development
  size: 5Gi

# Open WebUI Frontend Configuration
openWebUI:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: IfNotPresent
  service:
    # Use NodePort for local access
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30080
  # OIDC/SSO Configuration - disabled for local development
  sso:
    enabled: false
    clientId: ""
    clientSecret: ""
    providerUrl: ""
    providerName: ""
    scopes: ""

# ADK Backend Configuration
adkBackend:
  image:
    # Use the locally built ADK backend image
    repository: "adk-backend"
    tag: "local"
    pullPolicy: IfNotPresent
  port: 8000
  gcp:
    projectId: "agenticds-hackathon-54443"
    # Mount local gcloud credentials for authentication
    credentialsPath: "/Users/jeanfraga/.config/gcloud"
  env:
    # Enable Vertex AI for local testing with credentials
    GOOGLE_GENAI_USE_VERTEXAI: "TRUE"
    # Disable local mode since we have credentials
    ADK_LOCAL_MODE: "FALSE"

# Ingress Configuration - disabled for local development
ingress:
  enabled: false
  className: ""
  host: "localhost"
  annotations: {}
  tls:
    enabled: false
    secretName: ""

# Local development specific settings
local:
  # Expose services via NodePort for easy access
  exposeServices: true
  # Use host networking for easier debugging
  hostNetwork: false

# Ollama Proxy Configuration
ollamaProxy:
  image:
    # Use the locally built Ollama proxy image
    repository: "ollama-proxy"
    tag: "local"
    pullPolicy: IfNotPresent
  port: 11434
  logLevel: "INFO"
