model_list:
  - model_name: adk-data-science-agent
    litellm_params:
      model: openai/adk-data-science-agent
      api_base: http://adk-openai-adapter:8080/v1
      api_key: dummy
      custom_llm_provider: openai

  # Additional ADK models can be added here
  - model_name: data-science-agent
    litellm_params:
      model: openai/data-science-agent  
      api_base: http://adk-openai-adapter:8080/v1
      api_key: dummy
      custom_llm_provider: openai

litellm_settings:
  # Enable logging
  set_verbose: true
  
  # Custom model mapping for ADK agent
  model_fallbacks: [{"adk-data-science-agent": ["gpt-3.5-turbo"]}]
  
  # Request timeout settings
  request_timeout: 120
  
  # Enable CORS for web UI access
  cors_origins: ["*"]

general_settings:
  master_key: litellm-master-key-2024
  database_url: null  # Use in-memory for simplicity

router_settings:
  redis_host: null
  redis_port: null
  redis_password: null
