apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.releaseName }}
  labels:
    app: {{.Values.releaseName }}
spec:
  replicas: {{.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.releaseName }}
  template:
    metadata:
      labels:
        app: {{.Values.releaseName }}
    spec:
      {{- if .Values.workloadIdentity.enabled }}
      serviceAccountName: adk-backend-sa
      {{- end }}
      volumes:
        - name: open-webui-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.releaseName }}-data-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.adkBackend.gcp.credentialsPath }}
        - name: gcloud-credentials
          hostPath:
            path: {{.Values.adkBackend.gcp.credentialsPath }}
            type: Directory
        {{- end }}
      containers:
        # --- Open Web UI Frontend Container ---
        - name: open-webui
          image: "{{.Values.openWebUI.image.repository }}:{{.Values.openWebUI.image.tag }}"
          imagePullPolicy: {{.Values.openWebUI.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.openWebUI.service.targetPort }}
          env:
            - name: OLLAMA_BASE_URLS
              value: "http://localhost:{{.Values.ollamaProxy.port }}"
            {{- if .Values.openWebUI.sso.enabled }}
            # OAuth/SSO Configuration
            - name: ENABLE_OAUTH_SIGNUP
              value: "True"
            - name: OAUTH_PROVIDER_NAME
              value: {{.Values.openWebUI.sso.providerName | quote }}
            - name: OPENID_PROVIDER_URL
              value: {{.Values.openWebUI.sso.providerUrl | quote }}
            - name: OAUTH_SCOPES
              value: {{.Values.openWebUI.sso.scopes | quote }}
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.releaseName }}-oidc-secret
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.releaseName }}-oidc-secret
                  key: OAUTH_CLIENT_SECRET
            {{- end }}
            {{- if .Values.openWebUI.admin.autoCreate }}
            # Auto-create admin account
            - name: DEFAULT_USER_ROLE
              value: "admin"
            - name: DEFAULT_ADMIN_EMAIL
              value: {{.Values.openWebUI.admin.email | quote }}
            {{- if .Values.openWebUI.admin.password }}
            - name: ADMIN_USER_EMAIL
              value: {{.Values.openWebUI.admin.email | quote }}
            - name: ADMIN_USER_PASSWORD
              value: {{.Values.openWebUI.admin.password | quote }}
            {{- end }}
            {{- end }}
            # Authentication settings
            - name: ENABLE_SIGNUP
              value: "True"
            - name: ENABLE_LOGIN_FORM
              value: "True"
            - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
              value: "True"
            # Force authentication settings to override database
            - name: WEBUI_AUTH
              value: "True"
            # Force signup to be enabled (override database settings)
            - name: WEBUI_SIGNUP_ENABLED
              value: "True"
          volumeMounts:
            - name: open-webui-data
              mountPath: /app/backend/data
          {{- if .Values.openWebUI.resources }}
          resources:
            {{- toYaml .Values.openWebUI.resources | nindent 12 }}
          {{- end }}

        # --- Google ADK Backend Container (Sidecar) ---
        - name: adk-backend
          image: "{{.Values.adkBackend.image.repository }}:{{.Values.adkBackend.image.tag }}"
          imagePullPolicy: {{.Values.adkBackend.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.adkBackend.port }}
          env:
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "TRUE"
            - name: GOOGLE_CLOUD_PROJECT
              value: {{.Values.adkBackend.gcp.projectId | default "your-gcp-project-id" | quote }}
            - name: ADK_LOCAL_MODE
              value: "FALSE"
          {{- if .Values.adkBackend.gcp.credentialsPath }}
          volumeMounts:
            - name: gcloud-credentials
              mountPath: /home/appuser/.config/gcloud
              readOnly: true
          {{- end }}
          {{- if .Values.adkBackend.resources }}
          resources:
            {{- toYaml .Values.adkBackend.resources | nindent 12 }}
          {{- end }}

        # --- Ollama Proxy Container (Translation Layer) ---
        - name: ollama-proxy
          image: "{{.Values.ollamaProxy.image.repository }}:{{.Values.ollamaProxy.image.tag }}"
          imagePullPolicy: {{.Values.ollamaProxy.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.ollamaProxy.port }}
          env:
            - name: ADK_BACKEND_URL
              value: "http://localhost:{{.Values.adkBackend.port }}"
            - name: PROXY_PORT
              value: "{{.Values.ollamaProxy.port }}"
            - name: LOG_LEVEL
              value: "{{.Values.ollamaProxy.logLevel }}"
          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.ollamaProxy.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.ollamaProxy.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- if .Values.ollamaProxy.resources }}
          resources:
            {{- toYaml .Values.ollamaProxy.resources | nindent 12 }}
          {{- end }}