apiVersion: v1
kind: Service
metadata:
  name: {{.Values.releaseName }}-service
spec:
  type: {{.Values.openWebUI.service.type }}
  selector:
    app: {{.Values.releaseName }}
  ports:
    - protocol: TCP
      port: {{.Values.openWebUI.service.port }}
      targetPort: {{.Values.openWebUI.service.targetPort }}
      {{- if and (eq .Values.openWebUI.service.type "NodePort") .Values.openWebUI.service.nodePort }}
      nodePort: {{.Values.openWebUI.service.nodePort }}
      {{- end }}