apiVersion: v1
kind: Service
metadata:
  name: {{.Values.releaseName }}-service
spec:
  type: {{.Values.openWebUI.service.type }}
  selector:
    app: {{.Values.releaseName }}
  ports:
    - name: web
      protocol: TCP
      port: {{.Values.openWebUI.service.port }}
      targetPort: {{.Values.openWebUI.service.targetPort }}
      {{- if and (eq .Values.openWebUI.service.type "NodePort") .Values.openWebUI.service.nodePort }}
      nodePort: {{.Values.openWebUI.service.nodePort }}
      {{- end }}
    - name: ollama-api
      protocol: TCP
      port: {{.Values.ollamaProxy.port }}
      targetPort: {{.Values.ollamaProxy.port }}
      {{- if eq .Values.openWebUI.service.type "NodePort" }}
      nodePort: 30434
      {{- end }}