{{- if .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-backend-sa
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gcpServiceAccount }}
  labels:
    app: {{ .Values.releaseName }}
{{- end }}
